services:
  splitpro:
    image: splitpro
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "${PUBLIC_PORT:-3000}:3000"
    environment:
      ENV_FILE: /run/secrets/app_settings
    secrets:
      - app_settings
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: splitpro
      POSTGRES_USER: splitpro
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U splitpro"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  pgdata: {}

secrets:
  db_password:
    file: db_password.txt

  app_settings:
    file: .env.production
