services:
  splitpro:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: splitpro
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 3
    # Uncomment if you want to debug the database during development ONLY
    # ports:
    #   - 5432:5432

volumes:
  postgres-data: {}
